<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="OKCL129" failures="1" tests="2" name="Error Validation Test" time="11.036" errors="0" timestamp="2022-09-15T14:51:26 CDT">
  <testcase classname="com.end2end.submitTest" name="submitOrder" time="2.072">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.end2end.submitTest.submitOrder(submitTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:847)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="com.end2end.errorValidation" name="productDisplayedVerification" time="3.2"/>
  <testcase classname="com.end2end.errorValidation" name="LogInPageErrorValidation" time="0.0">
    <ignored/>
  </testcase> <!-- LogInPageErrorValidation -->
</testsuite> <!-- Error Validation Test -->
